theme: jekyll-theme-cayman
title:  Quora Insincere Question Classification
description: A project for EE 461P Data Science Principles at the University of Texas at Austin by Andy Chang, Clive Unger, Nick Edelman, Nic Key, and Avishka Suduwa Dewage.
exclude: [Notebooks/, Poster Presentation/, README.m, Gemfile, Gemfile.lock]
